### ISSUE TITLE
[BE] - добавить сущность Invite

### ISSUE THREAD

**Issue by ignavan39** [ignavan39/broker#22]
Добавить access - `moderator`

`moderator`, `admin` могут высылать инвайт на почту
инвайт должен иметь

ID - отправителя ( того кто пригласил ) человек не имеющий роль модератор или админ не должен иметь возможности отправить инвайт (403)
Email - email того кого хотят пригласить
WorkspaceId - ID отправителя должен присутствовать в данном воркспейсе в нужной роли
Status   - `pending` `accepted` `canceled`
**SystemStatus** - 'created`, `send`, `delivered`, `reject`
**Code** - Hash(workspace_id + sender_id + crypto_secret - по аналогии с хэшированием очередей добавить в env соль для хэширования)

при `SignUp` нужно найти все инвайты пользователя и изменить статус инвайта на `accepted` и выдать access `User`

сделать эндпоинт для админов / модераторов
- [ ] отправки инвайта
- [ ] просмтра всех инвайтов в рамках воркспейса
- [ ] отмена инвайта

в сущности `WorkspaceAccesses` изменить ключ `email` -> `userId`

***
переписать в signUp логику отправки кода
в SignUpPayload удалить код
и вместо кода присылать код инвайта и по нему искать уже инвайт
***

**Comment by enmex** [comment]
чем отличается модератор от админа?

**Comment by ignavan39** [comment]
Модератор не может удалить воркспейс и редачить воркспейс
Только приглашать пользователей
